language: node_js

addons:
  apt:
    update: true

node_js:
  - "0.11"

install:
  - npm install jshint -g
  - npm install PrettyCSS -g
  - npm install js-beautify -g

script:
  - jshint main.js
  - prettycss style.css
  - js-beautify --indent-size 2 --end-with-newline --outfile main.js.beautified main.js
  - diff --brief main.js main.js.beautified
