language: node_js

node_js:
  - "node"

env:
  global:
    - CC_TEST_REPORTER_ID=0cc7cb0a3b014fb35268001381151197c74f26ffd2c81ca93b82ab4e4538744a

addons:
  apt:
    update: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b85920202b6d9bac12fe
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

install:
  - npm install jshint PrettyCSS js-beautify html-linter -g
  - npm install
  - bundle install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./lint.sh
  - bundle exec danger
  - bundle exec jekyll build
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
