language: node_js

addons:
  apt:
    update: true

node_js:
  - "node"

install:
  - npm install jshint -g
  - npm install PrettyCSS -g
  - npm install js-beautify -g
  - npm install html-linter -g

script:
  - jshint main.js
  - prettycss style.css
  - html-linter --config html-linter.json *.html
  - |
    js-beautify \
      --type js \
      --indent-size 2 \
      --end-with-newline \
      --outfile main.js.beautified \
      main.js
  - diff -Naur main.js main.js.beautified
  - |
    js-beautify \
      --type css \
      --indent-size 4 \
      --end-with-newline \
      --outfile style.css.beautified \
      style.css
  - diff -Naur style.css style.css.beautified
  - |
    html-beautify \
      --type html \
      --indent-size 2 \
      --indent-inner-html \
      --end-with-newline \
      --outfile index.html.beautified \
      index.html
  - diff -Naur index.html index.html.beautified
  - |
    html-beautify \
      --type html \
      --indent-size 2 \
      --indent-inner-html \
      --end-with-newline \
      --outfile game.html.beautified \
      game.html
  - diff -Naur game.html game.html.beautified
