theme: jekyll-theme-hacker
title: Geometry Smash
google_analytics: UA-123354485-1
exclude:
  - vendor
  - CODEOWNERS
  - Dangerfile
  - node_modules
#baseurl: {{ site.baseurl }}
baseurl: geometry-smash
kramdown:
  auto_ids: true
plugins:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-toc
